# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
orbs:
  slack: circleci/slack@4.0
jobs:
  build-and-test:
    docker:
      - image: circleci/openjdk:11-browsers-legacy
      - image: circleci/mysql:8.0
        command: [--default-authentication-plugin=mysql_native_password]
        environment:
          MYSQL_DATABASE: 'in_food_dev'
          MYSQL_USER: 'in_food_user'
          MYSQL_PASSWORD: 'password'
          MYSQL_ROOT_PASSWORD: 'password'
          MYSQL_ROOT_HOST: "%"
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Wait for Database Connection
          # preinstalled in circleci/* docker image
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      #install mysql client
      - run: sudo apt-get install default-mysql-client
      - run: mysql -h 127.0.0.1 -u in_food_user -ppassword -e "create database if not exists in_food_dev"
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: mvn install -DskipTests
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
             - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      # run tests!
      - run: mvn integration-test
      - slack/notify:
          branch_pattern: production
          event: pass
          mentions: '@Julian'
          template: success_tagged_deploy_1
      - slack/notify:
          event: pass
          mentions: '@Julian'
          template: success_tagged_deploy_1
      - slack/notify:
          event: fail
          mentions: '@channel'
          template: basic_fail_1
workflows:
  send-notification:
    jobs:
      - build-and-test
