version: 2.1

orbs:
  slack: circleci/slack@4.1.1
slack-fail-post-step: &slack-fail-post-step
  post-steps:
    - slack/notify:
        branch_pattern: main
        channel: 'test-1'
        custom: |
          {
          	"blocks": [
          		{
          			"type": "header",
          			"text": {
          				"type": "plain_text",
          				"text": "❌ Build Failed on *${CIRCLE_BRANCH}*",
          				"emoji": true
          			}
          		},
          		{
          			"type": "section",
          			"fields": [
          				{
          					"type": "mrkdwn",
          					"text": "*Pipeline number:*\n#${CIRCLE_BUILD_NUM}"
          				},
          				{
          					"type": "mrkdwn",
          					"text": "*Time:*\n$(date +'%m/%d/%Y %T')"
          				}
          			]
          		},
          		{
          			"type": "section",
          			"fields": [
          				{
          					"type": "mrkdwn",
          					"text": "*Branch:*\n${CIRCLE_BRANCH}\n@channel"
          				}
          			]
          		},
          		{
          			"type": "actions",
          			"elements": [
          				{
          					"type": "button",
          					"text": {
          						"type": "plain_text",
          						"text": "View Job"
          					},
          					"style": "danger",
          					"url": "http://google.com"
          				}
          			]
          		}
          	]
          }
        event: fail

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-browsers-legacy
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: mvn install -DskipTests
      - run: mvn dependency:go-offline
  test:
    docker:
      - image: circleci/openjdk:11-browsers-legacy
      - image: circleci/mysql:8.0
        command: [ --default-authentication-plugin=mysql_native_password ]
        environment:
          MYSQL_DATABASE: 'in_food_dev'
          MYSQL_USER: 'in_food_user'
          MYSQL_PASSWORD: 'password'
          MYSQL_ROOT_PASSWORD: 'password'
          MYSQL_ROOT_HOST: "%"
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: mvn clean install
      - run: mvn dependency:go-offline
      - run: mvn integration-test
        
workflows:
  version: 2
  workflow:
    jobs:
      - build:
          <<: *slack-fail-post-step
      - test:
          requires:
            - build
          post-steps:
            - slack/notify:
                branch_pattern: main
                channel: 'test-1'
                custom: |
                  {
                  	"blocks": [
                  		{
                  			"type": "header",
                  			"text": {
                  				"type": "plain_text",
                  				"text": "❌ Test Failed on *${CIRCLE_BRANCH}*",
                  				"emoji": true
                  			}
                  		},
                  		{
                  			"type": "section",
                  			"fields": [
                  				{
                  					"type": "mrkdwn",
                  					"text": "*Pipeline number:*\n#${CIRCLE_BUILD_NUM}"
                  				},
                  				{
                  					"type": "mrkdwn",
                  					"text": "*Time:*\n$(date +'%m/%d/%Y %T')"
                  				}
                  			]
                  		},
                  		{
                  			"type": "section",
                  			"fields": [
                  				{
                  					"type": "mrkdwn",
                  					"text": "*Branch:*\n${CIRCLE_BRANCH}\n@channel"
                  				}
                  			]
                  		},
                  		{
                  			"type": "actions",
                  			"elements": [
                  				{
                  					"type": "button",
                  					"text": {
                  						"type": "plain_text",
                  						"text": "View Job"
                  					},
                  					"style": "danger",
                  					"url": "http://google.com"
                  				}
                  			]
                  		}
                  	]
                  }
                event: fail