version: 2.1
orbs:
  slack: circleci/slack@4.0
  
slack-fail-post-step: &slack-fail-post-step
  post-steps:
    - slack/notify:
        channel: 'test-1'
        custom: |
          {
            "text": "",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "❌ *Failure* #${CIRCLE_BUILD_NUM} `${CIRCLE_PROJECT_REPONAME}` on `${CIRCLE_BRANCH}`"
                }
              },
              {
                "type": "actions",
                "elements": [
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "View Job"
                    },
                    "url": "${CIRCLE_BUILD_URL}"
                  }
                ]
              }
            ]
          }
        event: fail

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-browsers-legacy
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: mvn install -DskipTests
      - run: mvn dependency:go-offline
  test:
    docker:
      - image: circleci/openjdk:11-browsers-legacy
      - image: circleci/mysql:8.0
        command: [ --default-authentication-plugin=mysql_native_password ]
        environment:
          MYSQL_DATABASE: 'in_food_dev'
          MYSQL_USER: 'in_food_user'
          MYSQL_PASSWORD: 'password'
          MYSQL_ROOT_PASSWORD: 'password'
          MYSQL_ROOT_HOST: "%"
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - run: mvn integration-test
        
workflows:
  version: 2
  workflow:
    jobs:
      - build:
          context:
            - slack
          <<: *slack-fail-post-step
      - test:
          context: [slack]
          requires:
            - build
          post-steps:
            - slack/notify:
                channel: 'test-1'
                custom: |
                  {
                    "text": "",
                    "blocks": [
                      {
                        "type": "section",
                        "text": {
                          "type": "mrkdwn",
                          "text": "✅ *Success* #${CIRCLE_BUILD_NUM} `${CIRCLE_PROJECT_REPONAME}` on `${CIRCLE_BRANCH}`"
                        }
                      },
                      {
                        "type": "actions",
                        "elements": [
                          {
                            "type": "button",
                            "text": {
                              "type": "plain_text",
                              "text": "View Job"
                            },
                            "url": "${CIRCLE_BUILD_URL}"
                          }
                        ]
                      }
                    ]
                  }
                event: always